// Project Database
const database = [
  {
    id: 123,
    projectName: 'SpendTrac Mobile Web App',
    projectDescription: 'SpendTrac is a Ruby on Rails mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.',
    featuredImage: 'https://i.postimg.cc/V6W0nVVC/spendtrac.jpg',
    technologies: ['Ruby on rails', 'Ruby', 'PostgreSQL', 'Bootstrap', 'ERB', 'HTML'],
    liveVersionUrl: 'https://salty-hamlet-02593.herokuapp.com/',
    sourceCodeUrl: 'https://github.com/Profsain/spendtrac',
  },
  {
    id: 124,
    projectName: 'Aplhablog',
    projectDescription: 'A Ruby on Rails application for creating new blog post, viewing posts, edit post, delete posts',
    featuredImage: 'https://i.postimg.cc/JnZvqbNJ/alphablog.jpg',
    technologies: ['Ruby on rails', 'Ruby', 'PostgreSQL', 'HTML', 'Bootstrap', 'ReactRedux'],
    liveVersionUrl: 'https://alpha-blog-app.herokuapp.com/',
    sourceCodeUrl: 'https://github.com/Profsain/alphablog',
  },
  {
    id: 125,
    projectName: 'Bookstore CMS',
    projectDescription: 'Bookstore CMS is a React application that allow user to add books their are currently reading to stores, display book list, update current chapter being read, add comment, monitor reading progress and also arrange books into various category. The project is built with React, Redux, and API.',
    featuredImage: 'https://i.postimg.cc/cC2r7G0X/bookstorecms.jpg',
    technologies: ['React', 'Redux', 'CSS', 'JavaScript', 'HTML', 'Microverse API'],
    liveVersionUrl: 'https://bookstore-react.herokuapp.com/',
    sourceCodeUrl: 'https://github.com/Profsain/Bookstore-CMS',
  },
  {
    id: 126,
    projectName: 'City-Weather App',
    projectDescription: 'A react-redux web app that helps users to search for weather conditions of any city, view location & date, view wind status & wind direction, view humidity, and air pressure, view weather conditions of the next 5 days, and convert from degrees Celsius to Fahrenheit or vice visa',
    featuredImage: 'https://i.postimg.cc/c4WfKsgJ/weatherapp.jpg',
    technologies: ['React', 'Redux', 'CSS', 'JavaScript', 'HTML'],
    liveVersionUrl: 'https://joyful-arithmetic-e662f9.netlify.app/weather',
    sourceCodeUrl: 'https://github.com/Profsain/city-weather',
  },
  {
    id: 127,
    projectName: 'Tin-Dog clone',
    projectDescription: 'A mobile responsive clone of the Tin-Dog website. Build with HTML, CSS, and Bootstrap',
    featuredImage: 'https://i.postimg.cc/hPcvHYkw/tindog.png',
    technologies: ['Bootstrap', 'CSS', 'JavaScript', 'HTML'],
    liveVersionUrl: 'https://profsain.github.io/Tin-Dog-Bootstrap_clone/',
    sourceCodeUrl: 'https://github.com/Profsain/Tin-Dog-Bootstrap_clone',
  },
  {
    id: 128,
    projectName: 'Space Travelers\' Hub',
    projectDescription: 'A React-Redux web application for a commercial and scientific space travel services company. Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or cancel the previously made booking. The Missions section displays a list of current missions along with their brief description. Users can join any of the missions by clicking the join mission button or leave the mission by clicking the leave mission button. The My Profile section displays all reserved rockets and joined missions. Users can cancel the reservation or leave the mission by clicking the respective buttons',
    featuredImage: 'https://i.postimg.cc/cJTFhXjV/spacexapp.jpg',
    technologies: ['React', 'Redux', 'CSS', 'JavaScript', 'HTML'],
    liveVersionUrl: 'https://tourmaline-cheesecake-5ae994.netlify.app/',
    sourceCodeUrl: 'https://github.com/Profsain/space-travel-hub',
  },
];
